FROM ubuntu
RUN apt-get update
RUN apt-get -y install libncurses5-dev libgnome2-dev libgnomeui-dev \
libgtk2.0-dev libatk1.0-dev libbonoboui2-dev \
libcairo2-dev libx11-dev libxpm-dev libxt-dev python-dev \
python3-dev ruby-dev lua5.1 liblua5.1-dev libperl-dev git
RUN python --version
RUN python3 --version
#apt remove vim vim-runtime gvim
#RUN cd ~ \
#&& git clone https://github.com/vim/vim.git \
#&& cd vim \
#&& ls
COPY vim /usr/src/vim 
RUN cd /usr/src/vim \
&& ./configure --with-features=huge \
--enable-multibyte \
--enable-rubyinterp=yes \
--enable-pythoninterp=yes \
--with-python-config-dir=/usr/lib/python2.7/config \
--enable-python3interp=yes \
--with-python3-config-dir=/usr/lib/python3.6/config \
--enable-perlinterp=yes \
--enable-luainterp=yes \
--enable-gui=gtk2 \
--enable-cscope \
--prefix=/usr/local
RUN cd /usr/src/vim \
&& make \
&& make install
RUN rm -rf /usr/src/vim
#    update-alternatives --install /usr/bin/editor editor /usr/local/bin/vim 1 && \
#    update-alternatives --set editor /usr/local/bin/vim && \
#    update-alternatives --install /usr/bin/vi vi /usr/local/bin/vim 1 && \
#    update-alternatives --set vi /usr/local/bin/vim && \
COPY pack ~/.vim/pack
COPY vimrc ~/.vim/vimrc
RUN rm ~/.vimrc
RUN mkdir /root/work
WORKDIR /root/work

ENTRYPOINT ["/usr/local/bin/vim"]
